"""Shared AHQ card data and application reference generation (standard library)."""
import json
from pathlib import Path
import textwrap

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / 'data/ahq-monsters.json').read_text(encoding='utf-8'))
SOURCE = DATA['source']
PAGES = DATA['pages']
STAT_LABELS = 'WS BS S T Sp Br Int W PV'.split()
BANDS = ['1-3', '4-12', '13-24', '25-36', '37+']


def validate():
    if len(PAGES) != 8 or any(len(page) != 8 for page in PAGES):
        raise ValueError('Expected eight source pages of eight cards')
    for page in PAGES:
        for m in page:
            if (len(m['stats']), len(m['hits']), len(m['ranged'])) != (9, 12, 7):
                raise ValueError(f"Incorrect cell count: {m['name']}")
            if not m['aliases'] or any(not a or '|' in a for a in m['aliases']):
                raise ValueError(f"Invalid aliases: {m['name']}")


def reference(m, page, slot):
    """Literal printed values: never compute hit rolls or choose a variant."""
    variants = [(p, c) for p, cards in enumerate(PAGES, 1)
                for c, card in enumerate(cards, 1) if card['name'] == m['name']]
    heading = m['name'].upper()
    if len(variants) > 1:
        heading += f' (variant {variants.index((page, slot)) + 1} of {len(variants)})'
    lines = [heading, '',
             ''.join(f'{s:>5}' for s in STAT_LABELS),
             ''.join(f'{s:>5}' for s in m['stats']), '',
             'HAND-TO-HAND COMBAT',
             'Target WS:' + ''.join(f'{s:>4}' for s in range(1, 13)),
             'Hit roll: ' + ''.join(f'{s:>4}' for s in m['hits']),
             'Damage dice: ' + (m['damage'] or '(blank in source)'), '',
             'RANGED COMBAT',
             'Range:    ' + ''.join(f'{s:>8}' for s in BANDS),
             'Hit roll: ' + ''.join(f'{s:>8}' for s in m['ranged'][:5]),
             'Max range: ' + (m['ranged'][5] or '(blank)') +
             '    Damage dice: ' + (m['ranged'][6] or '(blank)')]
    if not any(m['ranged']) or all(s == '-' for s in m['ranged']):
        lines.append('No ranged attack listed.')
    elif any('*' in s for s in m['ranged']):
        lines.append('* See source special rules.')
    lines += ['', 'EQUIPMENT / NOTES'] + textwrap.wrap(m['notes'], width=66)
    return '\r\n'.join(lines) + '\r\n\r\n'


def c_header():
    validate()
    lines = ['/* Generated by tools/generate-ahq-reference.py; edit data/ahq-monsters.json. */',
             'typedef struct { const char *aliases; const char *text; } AHQ_REFERENCE;',
             'static const AHQ_REFERENCE ahq_references[] = {']
    for page, monsters in enumerate(PAGES, 1):
        for slot, m in enumerate(monsters, 1):
            lines.append('  { ' + json.dumps('|'.join(a.lower() for a in m['aliases'])) + ',')
            for row in reference(m, page, slot).splitlines(keepends=True):
                # ASCII-only C string escapes also work in the legacy compiler.
                row.encode('ascii')
                lines.append('    ' + json.dumps(row))
            lines.append('  },')
    lines += ['};', '#define AHQ_REFERENCE_COUNT (sizeof(ahq_references) / sizeof(ahq_references[0]))', '']
    return '\n'.join(lines)
